apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ssl-httpbin-ingress
  namespace: istio-system
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  tls:
  - hosts:
    - ssl-httpbin.eastus.cloudapp.azure.com
  rules:
  - host: ssl-httpbin.eastus.cloudapp.azure.com
    http:
      paths:
      - backend:
          serviceName: istio-ingressgateway
          servicePort: 443
        path: /