apiVersion: v1

kind: Pod

metadata:
  name: result-app-prod
  lables:
      name: result-app-prod
      app: demo-voting-app

spec:
  containers:
    - name: result-app
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80